### ISSUE TITLE
Wrong min SDK name 

### ISSUE THREAD

**Issue by fakerqu** [canheo136/QuickLook.Plugin.ApkViewer#1]
Min SDK Level is 24 but SDK version name is Android 3.2(actually is Android 7)
![屏幕截图(1)](https://user-images.githubusercontent.com/29764984/87618610-dc8ea800-c74c-11ea-9c5a-9ea41f7a80ae.png)

**Comment by canheo136** [comment]
Thank for your contribution.
The issue will be fixed as soon as possible.
