### ISSUE TITLE
when Windows theme is light,this plugin can't preview correct

### ISSUE THREAD

**Issue by Atombuck** [canheo136/QuickLook.Plugin.ApkViewer#11]
when the windows theme is settled light,this plugin can't display correct,white bgcolor is wrong.

**Comment by littlef0x** [comment]
> when the windows theme is settled light,this plugin can't display correct,white bgcolor is wrong.

There's a small switch at the top right corner of the window, which is very hard to see with the light theme. Click it and the font color will turn black. However, you need to click it every time you use it. I also hope the author will add auto adaption feature to this plugin.

![screenshot](https://user-images.githubusercontent.com/32670075/149615716-d4b3e975-09aa-43e9-993b-bac63edd674e.png)

**Comment by eric1932** [comment]
> > when the windows theme is settled light,this plugin can't display correct,white bgcolor is wrong.
> 
> There's a small switch at the top right corner of the window, which is very hard to see with the light theme. Click it and the font color will turn black. However, you need to click it every time you use it. I also hope the author will add auto adaption feature to this plugin.

It's too hard to locate this button when in the light theme so I don't know this functionality at all until I enter this post. It would be better if the button is easier to identify.

![5b3da97f186a451193c42a9a4e914f0](https://user-images.githubusercontent.com/10938293/160529112-49321603-cce2-40ee-81af-3c0421b09d2a.png)

**Comment by canheo136** [comment]
Thank for your feedback.
Enjoy the new release! 😉
