### ISSUE TITLE
Show `versionCode` and `versionName`

### ISSUE THREAD

**Issue by Geeyun-JY3** [canheo136/QuickLook.Plugin.ApkViewer#4]
Show the `versionCode` and `versionName`, instead of just showing the `Version`.

**Comment by Geeyun-JY3** [comment]
Available in 1.2.0? Still cannot see the  `versionCode`

**Comment by Geeyun-JY3** [comment]
@canheo136

**Comment by canheo136** [comment]
I have a plan with UI (included your suggestion). But it's time for Lunar New Year, not for maintenance ;)
