### ISSUE TITLE
Dark "switch theme button" on dark theme

### ISSUE THREAD

**Issue by jakiisheep** [canheo136/QuickLook.Plugin.ApkViewer#5]
When I click on the button "switch theme" and I switch it to dark theme the button is dark instead of white

**Comment by canheo136** [comment]
Thank for your comment.
The "theme" which you change is background and font color. The button just transforms to notify "them changed successfully", it's black and always in black, that's not problem and you still know there's button in there.

**Comment by jakiisheep** [comment]
Yeah but doesn't it need to be white if its in a dark theme

**Comment by jakiisheep** [comment]
thank you very much for fixing this :D
