### ISSUE TITLE
预览APK报错

### ISSUE THREAD

**Issue by maomc** [canheo136/QuickLook.Plugin.ApkViewer#6]
![image](https://user-images.githubusercontent.com/20065601/106353209-d2687b80-6323-11eb-900e-9c7763f26540.png)
当我预览APK的时候提示了报错

**Comment by canheo136** [comment]
Thank for you comment.
Please sent me exception log (find [here](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location)), and apk file if you can.

**Comment by maomc** [comment]
========2021/2/1 11:38:52========
System.ArgumentException: 已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 AAPTForNet.ApkExtractor.createIconTable(List`1 positions, List`1 messages)
   在 AAPTForNet.ApkExtractor.ExtractLargestIcon(String path)
   在 AAPTForNet.AAPTool.Decompile(String path)
   在 QuickLook.Plugin.ApkViewer.Plugin.View(String path, ContextObject context)
   在 QuickLook.ViewerWindow.<>c__DisplayClass7_0.<BeginShow>b__1()
