### ISSUE TITLE
Support aab file

### ISSUE THREAD

**Issue by pnthach95** [canheo136/QuickLook.Plugin.ApkViewer#7]
> In the second half of 2021, new apps will be required to publish with the [Android App Bundle](https://developer.android.com/guide/app-bundle) on Google Play.

Can you make it to support aab file?

**Comment by canheo136** [comment]
Comment in Vietnamese

Khả năng hỗ trợ là không cao, chúng ta có một số vấn đề như sau:
1. Không thể tải trực tiếp file `.aab` từ google play -> khó tiếp cận -> khó test
2. Nó bao gồm nhiều modules -> thời gian trích xuất sẽ lâu hơn
3. Plugin hiện tại được hỗ trợ bởi `AAPT`. Vì vậy cho đến khi chắc chắn nó có thể hỗ trợ `.aab` (hoặc một công cụ khác) tôi sẽ xem xét đến việc hỗ trợ định dạng này.

Cám ơn bạn đã quan tâm.
