### ISSUE TITLE
Feature suggestion: Supported ABIs

### ISSUE THREAD

**Issue by Sominemo** [canheo136/QuickLook.Plugin.ApkViewer#8]
Fat APKs can contain multiple architectures (arm, x86, etc.), would be great if this plugin would support displaying a list of these like an [alternative plugin for MacOS](https://github.com/grishka/ApkQuickLook) does.
Thanks a lot!

**Comment by canheo136** [comment]
Thanks for your suggestion.
I will consider your ideal in my free time. But i can say that ability is fairly large, as long as supported by AAPT
