### ISSUE TITLE
Dark theme can't work on windows 11

### ISSUE THREAD

**Issue by Vixb1122** [canheo136/QuickLook.Plugin.ApkViewer#9]
Dark Theme
![image](https://user-images.githubusercontent.com/17810492/136515707-d926a35c-084c-4186-9429-7a711f262f40.png)
Light Theme
![image](https://user-images.githubusercontent.com/17810492/136515735-80f39b2c-b68a-472e-ac27-e1ffe1eb0bf1.png)

**Comment by RuoyuLee** [comment]
me too...

**Comment by ShlomoCode** [comment]
For me, too... :(
It looks awful like that, do not see anything
<img width="575" alt="image" src="https://user-images.githubusercontent.com/78599753/152988057-799bc23d-e816-4efd-a6e2-0bce8f045f5e.png">

**Comment by Joonel** [comment]
Same, guys... I'm using light theme only. 
![image](https://user-images.githubusercontent.com/69682842/159474930-f232044f-6d0a-487d-b9a0-894983d062b0.png)

**Comment by ShlomoCode** [comment]
@canheo136 How about creating a release for the new fix?
